version: '3.9'

services:
  db:
    image: postgres:9.6
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: library_system
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DEBUG: '1'
      DATABASE_NAME: library_system
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_HOST: db

volumes:
  postgres_data:
